{% set name = "identify" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pre-commit/identify/archive/v{{ version }}.tar.gz
  sha256: 76aa25108ec298193478735af763f761800a5c7d6aba43243018331177e0a798

build:
  number: 0
  skip: True  # [py<37]
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - ukkonen
    - python

test:
  imports:
    - identify
  requires:
    - pip
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - pip check
    - identify-cli --help
    - pytest tests  # [not win]
    # Some tests fail on Windows because they assume a Unix
    # file system, so they shouldn't lead to a hard fail
    # `pytest tests || 1` does not seem to work, so we need
    # to start a new subshell to just exit
    - pytest tests || cmd /c "exit /B 0"  # [win]

about:
  home: https://github.com/pre-commit/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python
  dev_url: https://github.com/pre-commit/identify
  doc_url: https://github.com/pre-commit/identify

extra:
  recipe-maintainers:
    - nicoddemus
    - tdegeus
    - deadsnakes-issues-bot
