{% set name = "identify" %}
{% set version = "1.0.13" %}
{% set hash_type = "sha256" %}
{% set hash_value = "70588542713a2a45c591c2d33128600f2352fc1f1c73217aeb81a3387eb14f2d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python setup.py install  --single-version-externally-managed --record=record.txt
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
