{% set name = "identify" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  sha256: 7e9a45564a370240f61a7aa996e085dea4c19e57353a8f4735260d762bd9834a

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - editdistance-s
    - python >=3.6

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
