{% set name = "identify" %}
{% set version = "1.4.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "4d38c81399fdc2e084907d2c7994d4aa9cffc0cad3e341318ed5d4d42ca78cf4" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - editdistance
    - python

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
