{% set name = "identify" %}
{% set version = "2.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pre-commit/identify/archive/v{{ version }}.tar.gz
  sha256: 8583903b5c25936fedf633348066cbfecce1c941dea3fcb51a6669db0e2a33d3

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - ukkonen
    - python >=3.6

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/pre-commit/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
    - tdegeus
    - deadsnakes-issues-bot
