{% set name = "identify" %}
{% set version = "2.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pre-commit/identify/archive/v{{ version }}.tar.gz
  sha256: 76aa25108ec298193478735af763f761800a5c7d6aba43243018331177e0a798

build:
  number: 0
  skip: True  # [py<37]
  script: python -m pip install . --no-deps --ignore-installed
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - ukkonen
    - python

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/pre-commit/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
    - tdegeus
    - deadsnakes-issues-bot
