{% set name = "identify" %}
{% set version = "1.1.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "09682323edc7a7fdc3e8bda8ab6c6175a6139690a83b249a8b8eae3904bc38cb" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
