{% set name = "identify" %}
{% set version = "2.4.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/pre-commit/identify/archive/v{{ version }}.tar.gz
  sha256: 8677b3909a21c65b3b5fcb30e06f35eea13a20d35d0fff1608021d07790c235b

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - ukkonen
    - python >=3.6

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/pre-commit/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
    - tdegeus
    - deadsnakes-issues-bot
