{% set name = "identify" %}
{% set version = "1.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  sha256: a32921cf290da5abca6612f03e82eac0b35a7255b6304226dda6596e4a8e8698

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - editdistance
    - python

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
