{% set name = "identify" %}
{% set version = "1.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/chriskuehl/identify/archive/v{{ version }}.tar.gz
  sha256: 36bb879bce2b7ca227b8c82dfc8bda7a56b9e3e8645ec44ab6e15f135c3980b8

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python
  entry_points:
    - identify-cli = identify.cli:main

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - editdistance
    - python >=3.6

test:
  imports:
    - identify
  requires:
    - pytest
  source_files:
    - LICENSE
    - tests
    - setup.py
  commands:
    - identify-cli --help
    - pytest tests

about:
  home: https://github.com/chriskuehl/identify
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: File identification library for Python

extra:
  recipe-maintainers:
    - nicoddemus
