travis:
  secure:
    BINSTAR_TOKEN: lUql656bfmKu4cSlrN6q2tcTsXkHUzX7liWEW9RepaZycyJUJ9Gh+wZjAJSFSZLHti4zi0E9ZxjsfeT+BAjc3UBHVFoeG9bZqQAhA7g+l1td2Y5HgwODooWXAl4pdUh547g7r0T6hXGo8Z6PJHv6PdQcKh+nIdrvsKqHe7zO+Tqs3BfXuNqdImG5SqV5R4opOWm1DjwFz+QHWY7kXMnUmScXgZej//p5rx41mZKI7OnblCYaygpzpHv6xd8uEFH/9xMGxpeAicIwGn4OyzXDTeAZD4qGSKi5Qbqc/tIcY05SsAnVV1gT6zjD46JZsRzyodZw4zFXINaQanO2xY+Pz2YS5S99Wwzhdk1ZmUEB0Z1SiPv8IjTWPAtzeoyX5eCIxN9TDL7G9yhCNxyAmxQcPyVSSZmHJ5q9p5Is0qWIwk3RMx10xmBSGVDbd06FvOh4Jg6eDbcaw7ZPVjX4GL/MdzY2YszcUSZ9B0r6TbPXCBsScCKVdGGgq9zDUctK4wLC5JA8Jw3g2wVr6qDYGqA45jYbBsg07ckxxt+wJQPC5IadRQTKyWqnG9kDBz9zL2SIU7ebmRXJkhW2CUmFcSgBGnBIODYf9HXOkkPtXCbkNmqCsehXaz/YT68NZqTeKHQLUG0xwq+jp7J1SFhKFNLmhw/BKO8vsXUqTx/cPXjV6lc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
bot:
  automerge: true
