travis:
  secure:
    BINSTAR_TOKEN: uFzMPH6/zkpIVs9HSELevghk9F05BjCOVGfy5Y5BQ+F9Z4ZjlCrHul8Xd2z0hCXqh7aoLLw55xHMGlhrmYm1hvbQNvJFhB6flJB0/wRA44rdWQsZUUzTaWnOLaOU1nzlLFpj9hqfqhNwqH0x8T0CO2LYRZRmMRFIQesaw3jQDJ3Bbq/xNIn684TrZAKKgMhXpIV6FI+ThwoPov3P4a0lxVaJZD8kdcjBFb78S+nCZMKYqo8FxCEkgS0K6W+Sa5Du+VQVRApfkN9hXfbzeS+Smh+52HfmHQyQ72ByXEZq3aA8IpJp/WsDhowycyFU1AU1gcOQK5WNFVAg6Gj3Sb1KtSY2gKE6nTg8iN/r5ke9y0bReilRXiUVf496lLqRgjQ/0EvbJ88uce3FOLufSpkW+jtOK2bFgexBh4UL0Fag/p0S9lgkXtNhoTZaNcfLFmf0z0MPZg7hJvNy+6je80F2BXJOGboY0eB8bSXlhvv5x+ttru1ed3XTgcusM0fPoEHEjeO8de4Dhvo8kR53dg24qkymsKjZXplkGSGrZJs9ugVNxn5hJlPx4P5AZWgTvctmLT3r8yjKPjskGAuS3yPK0WXGl5As7F8VG0yzUviDQ5eql3vzuXGF5//rwI0EF4zN7SAvWYKm4fceCus2CNOC+rNMN5vwxwozyKUsPNS9SSY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
